[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.15"
eframe = "0.15"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8.4"
mysql = "16.1.0"
bsod = "0.1.1"
winit = "0.30.0"

[package.metadata.windows]
resource = ["bank.exe.manifest"]