[package]
name = "glosor"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.26.0", features = ["bundled"] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


